---
Title: "collaborator-analysis a07"
Author: Leticia Pereira
Repo: tokay-leticia
Format: html
---
## Exercise: Explore, Clean, and Wrangle Data
#importaing packages
```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(here)
```
# reading in the data
```{r}
lobster_traps = read_csv(here::here("data/Lobster_Trap_Counts_All_Years_20210519.csv"))
head(lobster_traps)

```
#Convert missing values using mutate() and na_if()
```{r}
lobster_traps = lobster_traps %>% 
    mutate(TRAPS = na_if(TRAPS, -99999))

unique(lobster_traps)

```
#filter
```{r}
not_napl = lobster_traps %>% 
    filter(SITE != "NAPL")

carp_20_traps = lobster_traps %>% 
    filter(SITE == "CARP" & TRAPS > 20)

# `group_by() %>% summarize()` practice
max_lobster_traps = lobster_traps %>% 
    group_by(SITE, MONTH) %>%
    summarize(MAX_TRAPS = max(TRAPS, na.rm = TRUE))
```
## Exercise: Data Visualization
```{r}
ggplot(data = lobster_traps, aes(x = TRAPS)) +
    geom_histogram() +
    facet_wrap( ~ YEAR)
```
```{r}
lobsters_traps_summarize = lobster_traps %>% 
  group_by(SITE, YEAR) %>% 
  summarize(TOTAL_TRAPS = sum(TRAPS, na.rm = TRUE))
```
```{r}
# line plot
ggplot(data = lobsters_traps_summarize, aes(x = YEAR, y = TOTAL_TRAPS)) +
    geom_line(aes(color = SITE))

```
```{r}
# line and point plot
ggplot(data = lobsters_traps_summarize, aes(x = YEAR, y = TOTAL_TRAPS)) +
    geom_point(aes(color = SITE)) 
    geom_line(aes(color = SITE))


# I think this looks better?
```
```{r}
lobster_traps_fishing_pressure = lobster_traps %>% 
    filter(YEAR %in% c(2019, 2020, 2021)) %>%
    mutate(FISHING_PRESSURE = if_else(TRAPS >= 8, true = "high", false = "low")) %>%
    group_by(SITE, FISHING_PRESSURE) %>%
    summarize(COUNT = n()) %>%
    drop_na()
```
```{r}
# bar plot
ggplot(data = lobster_traps_fishing_pressure, aes(x = SITE, y = COUNT, fill = FISHING_PRESSURE)) +
    geom_col() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
# I prefer the stacked figure
```

```{r}
# dodged bar plot
ggplot(data = lobster_traps_fishing_pressure, aes(x = SITE, y = COUNT, fill = FISHING_PRESSURE)) +
    geom_col(position = "dodge") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))

# I dont like this one 
```
```


