---
title: "lobster-report"
format: html
author: "Tokay and Leticia"
---

## Introduction

The dataset used in this assignment was sourced from the EDI Data Portal and concerns the size and abundance of California spiny lobsters in Santa Barbara. Spiny lobsters are predators that serve as an essential predator species in kelp forests, and are a species that are harvested by humans for food. They are managed both as an indicator of kelp forest health and as a food source that can be overfished if too many adults of highly reproductive size are removed from the environment. This dataset contains size and abundance counts of spiny lobsters across sites and years, as well as trap counts by year and site.

Santa Barbara Coastal LTER, D. Reed, and R. Miller. 2022. SBC LTER: Reef: Abundance, size and fishing effort for California Spiny Lobster (Panulirus interruptus), ongoing since 2012 ver 8. Environmental Data Initiative. https://doi.org/10.6073/pasta/25aa371650a671bafad64dd25a39ee18 (Accessed 2026-04-13).

The data was downloaded here: <https://portal.edirepository.org/nis/mapbrowse?packageid=knb-lter-sbc.77.8> on April 13, 2026

## Owner Analysis

fig.1

fig.2

## Collaborator Analysis

## Summary

Our analysis shows that particular sites contain very different sizes and numbers of lobsters in their surveyed populations.
