---
title: "owner-analysis"
format: html
author: "Tokay Alberts"
---

## Exercise: Explore, Clean, and Wrangle Data

```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(here)
```

```{r}
lobster_abundance <- read_csv(here::here("data/Lobster_Abundance_All_Years_20220829.csv"))
```

## cleaning data, delete later

```{r}
lobster_abundance <- lobster_abundance %>% 
    mutate(SIZE_MM = na_if(SIZE_MM, -99999))

not_napl <- lobster_abundance %>% 
    filter(SITE != "NAPL")

aque_70mm <- lobster_abundance %>% 
    filter(SITE == "AQUE" & SIZE_MM >= 70)

# `group_by() %>% summarize()` practice

max_lobster <- lobster_abundance %>% 
  group_by(SITE, MONTH) %>% 
  summarize(MAX_LENGTH = max(SIZE_MM, na.rm = TRUE))
```

## Exercise: Data Visualization

```{r}
lobsters_summarize <- lobster_abundance %>% 
  group_by(SITE, YEAR) %>% 
  summarize(COUNT = n())

# line and point plot
fig1<- ggplot(data = lobsters_summarize, aes(x = YEAR, y = COUNT)) +
  geom_point(aes(color = SITE)) +
  geom_line(aes(color = SITE))
fig1 <- fig1 + labs(title = "Count of CA spiny lobster by year", caption = "Figure 1: Count of CA spiny lobsters by year, tracked by site. The site with the highest peak count, IVEE, is a MPA.", Position = "left") + theme_minimal()

fig1

ggsave("fig1.png", plot = fig1, path = "../figs/")
```

```{r}
lobster_size_lrg <- lobster_abundance %>%
    filter(YEAR %in% c(2019, 2020, 2021)) %>%
    mutate(SIZE_BIN = if_else(SIZE_MM <= 70, true = "small", false = "large")) %>%
    group_by(SITE, SIZE_BIN) %>%
    summarize(COUNT = n()) %>%
    drop_na()

# bar plot
fig2 <- ggplot(data = lobster_size_lrg, aes(x = SITE, y = COUNT, fill = SIZE_BIN)) +
    geom_col()

fig2 <- fig2 + labs(title = "Distribution of CA spiny lobster size by site", caption = "Figure 2: Count of CA spiny lobsters by site, split by size. The site with the most large lobsters, IVEE, is a MPA.") + theme_minimal()

fig2

ggsave("fig2.png", plot = fig2, path = "../figs/")
```

## 
